id: rel01.1-uc001-go-install
title: Go Install
summary: |
  A developer installs the cupboard CLI via go install and verifies it works
  by initializing a cupboard and performing basic operations. This validates
  that the module is installable from the Go toolchain and the binary lands
  in $GOBIN.
actor: Developer or agent with a Go toolchain (1.25+) installed
trigger: Wanting to use cupboard on a new machine or in a new project
flow:
  - F1: "Install cupboard binary: run go install github.com/mesh-intelligence/crumbs/cmd/cupboard@latest"
    detail: |
      The Go toolchain downloads the module, builds cmd/cupboard, and places
      the binary in $GOBIN (defaults to $GOPATH/bin, typically ~/go/bin).
  - F2: "Verify binary accessible: run cupboard --help"
    detail: |
      The CLI prints usage information showing available commands (init, set,
      get, list, delete).
  - F3: "Initialize cupboard: run cupboard init in a project directory"
    detail: |
      This creates the data directory (prd-configuration-directories R2.1, R2.5)
      and configuration directory (R1.6). The JSONL files (crumbs.jsonl,
      trails.jsonl, etc.) are created empty per prd-sqlite-backend R4.1, R1.4.
  - F4: "Create a crumb: run cupboard set crumbs with JSON payload"
    detail: |
      The CLI calls cupboard.GetTable("crumbs").Set() (prd-cupboard-core R2.3,
      R3.3). The backend generates a UUID v7 (R8.2) and returns the created
      crumb as JSON.
  - F5: "List crumbs: run cupboard list crumbs to confirm persistence"
    detail: |
      The CLI calls cupboard.GetTable("crumbs").Fetch() with an empty filter
      to return all crumbs. The output includes the crumb created in step F4.
touchpoints:
  - T1: "cmd/cupboard: CLI binary built by go install"
  - T2: "pkg/types: Config struct, entity types (prd-cupboard-core R1)"
  - T3: "internal/sqlite: Backend that creates JSONL files and SQLite cache (prd-sqlite-backend R1, R4)"
  - T4: "internal/paths: Resolves default config and data directories (prd-configuration-directories R1, R2)"
success_criteria:
  - S1: go install github.com/mesh-intelligence/crumbs/cmd/cupboard@latest completes without errors
  - S2: cupboard --help prints usage from $GOBIN
  - S3: cupboard init creates the data directory with JSONL files
  - S4: cupboard set crumbs and cupboard list crumbs round-trips a crumb
  - S5: No manual compilation steps required beyond go install
out_of_scope:
  - Package managers (brew, apt, snap)
  - Docker-based installation (see rel99.0-uc002-docker-bootstrap)
  - Version management or update mechanisms
  - Cross-compilation or release binaries (goreleaser, GitHub releases)
test_suite: test-rel01.1-uc001-go-install
dependencies:
  - D1: "prd-cupboard-core: R1, R2, R3, R8 (Config struct, Cupboard and Table interfaces, UUID v7 generation)"
  - D2: "prd-configuration-directories: R1, R2 (CLI config directory, backend data directory)"
  - D3: "prd-sqlite-backend: R1, R4, R5 (Data directory layout, startup sequence, write operations)"
  - D4: "Go module published to proxy: The module must be available on the Go module proxy (public repository, tagged)"
demo: |
  # Install via go install
  go install github.com/mesh-intelligence/crumbs/cmd/cupboard@latest

  # Verify binary is accessible
  cupboard --help

  # Initialize cupboard in project
  cd ~/my-project
  cupboard init

  # Create and list crumbs
  cupboard set crumbs "" '{"Name":"First crumb","State":"draft"}'
  cupboard list crumbs

  # For local-only use before publishing:
  git clone https://github.com/mesh-intelligence/crumbs.git
  cd crumbs
  go build -o cupboard ./cmd/cupboard
references:
  - prd-cupboard-core
  - prd-configuration-directories
  - prd-sqlite-backend
