id: rel99.0-uc001-blazes-templates
title: Agent Uses Blazes (Workflow Templates)
summary: |
  A coding agent discovers predefined workflow templates (blazes) from a template
  directory, reads template metadata to understand available workflows, and selects
  a template based on semantic match to the current task. This tracer bullet validates
  the template discovery and selection flow that enables agents to reuse common
  workflow patterns.
actor: Coding agent (e.g., Claude Code) that needs to perform a recognized workflow pattern such as bug fixing, feature implementation, or code review
trigger: Agent encountering a task that matches a known workflow category; instead of constructing a workflow from scratch, the agent discovers and selects a predefined template
flow:
  - F1: "Discover template directory: locate the template directory configured via Cupboard or a well-known path such as .crumbs/blazes/"
  - F2: "List available templates: read the directory and enumerate all .yaml or .yml files, each representing one blaze"
  - F3: "Read template metadata: parse each template YAML and extract name, description, tags, and parameters without parsing the full trail definition"
  - F4: "Match task to template: compare current task context against template metadata using tags for semantic matching (e.g., task fix the login bug matches templates tagged with bug-fix, debugging)"
  - F5: "Select template: choose the best-matching template; if multiple match, prompt user or select based on priority or specificity"
  - F6: "Extract parameters: read the parameters section with name, description, type, and optional default; determine which can be inferred from context and which require user input"
  - F7: "Present selection: display selected template name, description, and required parameters to the user for confirmation"
touchpoints:
  - T1: "Template directory: file system path containing blaze YAML files"
  - T2: "YAML parser: reads and parses template files into structured data"
  - T3: "Template metadata: name, description, tags, parameters extracted from YAML"
  - T4: "Parameter extraction: identifies required inputs before instantiation"
  - T5: "prd-crumbs-interface R1: Crumb struct fields referenced in template trail definition"
  - T6: "prd-trails-interface R3: trail creation referenced for future instantiation"
  - T7: "prd-trails-interface R7: belongs_to links for crumb-trail membership in instantiation"
success_criteria:
  - S1: Agent discovers template directory at configured or well-known path
  - S2: Agent lists all .yaml/.yml files in the directory
  - S3: Agent parses template metadata (name, description, tags, parameters) without error
  - S4: Agent matches a task description to template tags
  - S5: Agent selects the best-matching template
  - S6: Agent extracts parameter definitions (name, type, description, default)
  - S7: Agent presents selected template and parameters to user
out_of_scope:
  - Trail instantiation from template (requires prd-blazes-instantiation)
  - Parameter value binding and placeholder expansion (requires prd-blazes-instantiation)
  - Creating crumbs via Table.Set per prd-crumbs-interface R3 (requires prd-blazes-instantiation)
  - Creating trails via Table.Set per prd-trails-interface R3 (requires prd-blazes-instantiation)
  - Creating belongs_to links per prd-trails-interface R7 (requires prd-blazes-instantiation)
  - Template validation and error handling for malformed YAML (requires prd-blazes-schema)
  - Template versioning or inheritance
  - Remote template repositories
  - Template creation or editing workflows
test_suite: TBD
dependencies:
  - D1: File system access to template directory
  - D2: YAML parsing capability (standard library or dependency)
  - D3: Agent context for semantic matching (task description, tags)
risks:
  - K1: "No templates in directory | Return empty list gracefully; agent proceeds without template"
  - K2: "Malformed YAML in template file | Skip invalid templates with warning; do not fail entire discovery"
  - K3: "Multiple templates match equally | Define selection heuristics (most specific tags, user preference)"
  - K4: "Template schema evolves | Version field in template enables migration; validate against schema"
  - K5: "Large template directory slows discovery | Cache parsed metadata; lazy-load trail definitions"
references:
  - prd-crumbs-interface (R1 Crumb struct, R2 State values, R9 Filter map)
  - prd-trails-interface (R1 Trail struct, R2 State values, R3 Trail creation)
  - prd-stash-interface (R2 Stash types context and artifact)
demo: |
  # 1. List available templates
  ls .crumbs/blazes/*.yaml

  # 2. Show template metadata (name, description, tags)
  yq '.name, .description, .tags' .crumbs/blazes/bug-fix.yaml

  # 3. Show required parameters
  yq '.parameters[] | .name + ": " + .description' .crumbs/blazes/bug-fix.yaml

  # 4. Agent matches task "fix the login crash" to bug-fix template
  # (semantic matching logic in agent)

  # 5. Agent displays selection
  # Selected template: Bug Fix
  # Description: Investigate and fix a reported bug with proper testing
  # Parameters needed:
  #   - bug_description (text): Short description of the bug
  #   - reproduction_steps (text): Steps to reproduce the bug
  #   - affected_files (list): Files likely affected by the bug
